<a href="https://colab.research.google.com/github/napgat/PythonLab3/blob/main/Lab5-5069.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา : 67015069 ชื่อ : นายนภัทร แสงวัง

Exercise 5.1 ให้เขียน function ชื่อ day_of_year(day, month ,year) โดยมีการคืนค่า คือ day_of_years เป็นวันที่ลำดับที่เท่าใดของปีคริสตศักราช year
ปีที่เป็น Leap Year เดือนกุมภาพันธ์จะมี 29 วัน
ให้สร้างฟังก์ชัน is_leap เพื่อตรวจสอบ leap year แยกออกมา และให้ฟังก์ชัน day_of_year เรียกใช้ is_leap อีกที


In [ ]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def is_leap(year):
    if year % 4 == 0 and (year % 100 != 0 or year % 400 == 0):
        return True
    else:
        return False
def day_of_year(day, month, year):
    total_day =0
    total_day += day
    if month > 1:
        total_day += month_to_day(month-1,year)
    return total_day


def month_to_day(month,year):
    day_month = 0
    for i in range(month):
        if i == 1 and is_leap(year) is True:
            days_in_month[1] += 1
        day_month += days_in_month[i]
        days_in_month[1] = 28
    return day_month

# Testcases
print("Normal year (2023):")
print(f"1 Jan 2023: {day_of_year(1, 1, 2023)}")  # ควรได้ 1
print(f"1 Feb 2023: {day_of_year(1, 2, 2023)}")  # ควรได้ 32
print(f"1 Mar 2023: {day_of_year(1, 3, 2023)}")  # ควรได้ 60
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

print("\nLeap year (2024):")
print(f"1 Jan 2024: {day_of_year(1, 1, 2024)}")  # ควรได้ 1
print(f"29 Feb 2024: {day_of_year(29, 2, 2024)}")  # ควรได้ 60
print(f"1 Mar 2024: {day_of_year(1, 3, 2024)}")  # ควรได้ 61
print(f"31 Dec 2024: {day_of_year(31, 12, 2024)}")  # ควรได้ 366

print("\nCentury year, not a leap year (1900):")
print(f"1 Mar 1900: {day_of_year(1, 3, 1900)}")  # ควรได้ 60

print("\nCentury year, leap year (2000):")
print(f"1 Mar 2000: {day_of_year(1, 3, 2000)}")  # ควรได้ 61

print("\nMid-year dates:")
print(f"15 Jun 2023: {day_of_year(15, 6, 2023)}")  # ควรได้ 166
print(f"15 Jun 2024: {day_of_year(15, 6, 2024)}")  # ควรได้ 167 (Leap year)

print("\nLast day of each quarter:")
print(f"31 Mar 2023: {day_of_year(31, 3, 2023)}")  # ควรได้ 90
print(f"30 Jun 2023: {day_of_year(30, 6, 2023)}")  # ควรได้ 181
print(f"30 Sep 2023: {day_of_year(30, 9, 2023)}")  # ควรได้ 273
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

Normal year (2023):
1 Jan 2023: 1
1 Feb 2023: 32
1 Mar 2023: 60
31 Dec 2023: 365

Leap year (2024):
1 Jan 2024: 1
29 Feb 2024: 60
1 Mar 2024: 61
31 Dec 2024: 366

Century year, not a leap year (1900):
1 Mar 1900: 60

Century year, leap year (2000):
1 Mar 2000: 61

Mid-year dates:
15 Jun 2023: 166
15 Jun 2024: 167

Last day of each quarter:
31 Mar 2023: 90
30 Jun 2023: 181
30 Sep 2023: 273
31 Dec 2023: 365


Exercise 5.2 ให้เขียนฟังก์ชัน เพิ่มเติมเป็น date_diff
รับข้อมูลในรูปแบบ “dd-mm-yyyy” เช่น date_diff(“1-1-2018”, “1-1-2020”) จะได้ 731 วัน date_diff(“25-12-1999”, “9-3-2000”) จะได้ 76 วัน
ให้เขียนฟังก์ชัน day_in_year โดยจะส่งค่าจำนวนวันของปี (365 หรือ 366) โดยรับข้อมูลเป็น ปี
ส่งคืนข้อมูลเป็นจำนวนวันตั้งแต่วันที่แรก จนถึงวันที่สอง โดยรวมทั้ง 2 วันนั้นเข้าไปด้วย
ให้สมมติว่าวันแรก จะต้องมาก่อนวันที่สองเสมอ ดังนั้นไม่ต้องตรวจสอบ


In [ ]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
def is_leap(year):
    if year % 4 == 0 and (year % 100 != 0 or year % 400 == 0):
        return True
    else:
        return False
def day_of_year(day, month, year):
    total_day =0
    total_day += day
    if month > 1:
        total_day += month_to_day(month-1,year)
    return total_day


def month_to_day(month,year):
    day_month = 0
    for i in range(month):
        if i == 1 and is_leap(year) is True:
            days_in_month[1] += 1
        day_month += days_in_month[i]
        days_in_month[1] = 28
    return day_month


def day_in_year(year):
    return 366 if is_leap(year) else 365


def date_diff(date1, date2):
    day1,month1,year1 = split_date(date1)
    day2,month2,year2 = split_date(date2)
    year_diff = 0
    month_diff = 0
    year1_dayleft = 0
    year2_daystart = 0
    if year2 != year1:
        for i in range(year1+1,year2):
            year_diff += day_in_year(i)
        year1_dayleft = day_in_year(year1) - day_of_year(day1,month1,year1) + 1
        year2_daystart = day_of_year(day2,month2,year2)
        dayofall = year_diff + year1_dayleft + year2_daystart
    elif year2 == year1:
        for i in range(month1+1,month2):
            month_diff += days_in_month[i-1]
        day1_left = days_in_month[month1-1] - day1 + 1
        dayofall = month_diff + day1_left + day2
    return dayofall


def split_date(date):
    day,montn,year = date.split('-')
    return int(day),int(montn),int(year)

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)



731
76
367
366
366
365


Exercise 5.3 จากโปรแกรม 5.2 ให้เขียนฟังก์ชัน date_diff  เพิ่มเติม โดยให้มีการตรวจสอบ
วันที่ต้องเป็นวันที่ถูกต้องของเดือนนั้นๆ
เดือนต้องอยู่ระหว่าง 1-12
เดือนกุมภาพันธ์ของปีที่มี Leap Year เท่านั้นที่จะมี 29 วันได้
หากข้อมูล Input ผิดพลาด ให้ Return -1


In [ ]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
def is_leap(year):
    if year % 4 == 0 and (year % 100 != 0 or year % 400 == 0):
        return True
    else:
        return False
def day_of_year(day, month, year):
    total_day =0
    total_day += day
    if month > 1:
        total_day += month_to_day(month-1,year)
    return total_day


def month_to_day(month,year):
    day_month = 0
    for i in range(month):
        if i == 1 and is_leap(year) is True:
            days_in_month[1] += 1
        day_month += days_in_month[i]
        days_in_month[1] = 28
    return day_month


def day_in_year(year):
    return 366 if is_leap(year) else 365


def date_diff(date1, date2):
    if check_format(date1) == True and check_format(date2) == True:
        day1,month1,year1 = split_date(date1)
        day2,month2,year2 = split_date(date2)
        if check_error_day(day1,month1,year1) == True and check_error_day(day2,month2,year2) == True :
            year_diff = 0
            month_diff = 0
            year1_dayleft = 0
            year2_daystart = 0
            if year2 != year1:
                for i in range(year1+1,year2):
                    year_diff += day_in_year(i)
                year1_dayleft = day_in_year(year1) - day_of_year(day1,month1,year1) + 1
                year2_daystart = day_of_year(day2,month2,year2)
                dayofall = year_diff + year1_dayleft + year2_daystart
            elif year2 == year1:
                for i in range(month1+1,month2):
                    month_diff += days_in_month[i-1]
                day1_left = days_in_month[month1-1] - day1 + 1
                dayofall = month_diff + day1_left + day2
            return dayofall
    return -1


def check_error_day(day,month,year):
    if is_leap(year) == True:
        days_in_month[1] += 1
    if month <= 12:
        if day <= days_in_month[month-1]:
            return True
    return False


def check_format(date):
    if date[1] == '-' or date[2] == '-':
        if date[3] == '-' or date[4] =='-' or date[5] == '-':
            return True
    return False

def split_date(date):
    day,montn,year = date.split('-')
    return int(day),int(montn),int(year)

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

# ทดสอบกรณีข้อมูลไม่ถูกต้อง
print(date_diff("31-4-2023", "1-5-2023"))  # ควรได้ -1 (เดือนเมษายนมี 30 วัน)
print(date_diff("29-2-2023", "1-3-2023"))  # ควรได้ -1 (ปี 2023 ไม่ใช่ leap year)
print(date_diff("1-13-2023", "1-1-2024"))  # ควรได้ -1 (เดือนไม่ถูกต้อง)
print(date_diff("abc", "1-1-2024"))  # ควรได้ -1 (รูปแบบวันที่ไม่ถูกต้อง)

731
76
367
366
366
365
-1
-1
-1
-1


1.	ปลาหมอคางดำเพศเมีย 1 ตัว เมื่ออายุครบ 2 เดือน จะสามารถสืบพันธ์ได้ โดยระยะเวลาตั้งท้องจนถึง
วางไข่ของตัวเมียจะใช้เวลา 21 วัน และฟักในปากเพศผู้อีก 7 วัน (สามารถรวมเป็น 1 เดือนได้) โดยออกไข่ครั้งละ 300 ฟอง กำหนดให้ไข่ฟักเป็นเพศผู้และเพศเมียอย่างละครึ่ง และเมื่อวางไข่แล้วจะสามารถสืบพันธ์ต่อได้ทันที กำหนดให้ปลามีอายุ 5 ปี และปลาทั้งหมดจะตาย p% ทุก 1 เดือน จงหาว่าปลาหมอคางดำหลุดจากฟาร์ม n ตัวเป็นเพศผู้และเพศเมียอย่างละครึ่ง จงเขียนโปรแกรมรับค่า n และ p ให้แสดงผลจำนวนปลาทุก 3 เดือน เป็นเวลา 10 ปี ให้เขียนเป็นฟังก์ชัน ชื่อ simulate_fish_population()


In [ ]:
import math
def simulate_fish_population(n, p,month=3):
  year_offish = []
  adult_fish = 0
  baby_fish = 0
  remove = 0
  for y in range(1,11):
    for i in range(month,12+1):
      if i <= 3:
        pp_born = n // 2 #เริ่มต้น ปลาจับคู่ผสมพันธ์ 2 ตัวต่อ 1 คู่จะกลายเป็น 1 คู่
        egg_pp = pp_born * 300 #เดือนแรก 1 คู่ 1คู่ออกไข่ได้ 300 ฟองเป็น 1 * 300 = 300

        baby_fish = egg_pp - (egg_pp*0.1) #เดือนที่สอง จากไข่กลายเป็นโดยเป็นลูกปลา แต่ลดลง10% = ไข่ที่ลดไปแล้ว 10%
        egg_pp = pp_born * 300 #เดือนที่สอง 1 คู่ที่พร้อมผสมพันธ์จะผสมพันธ์กันแล้วออกไข่ในเดือนที่สองทันที่ 1 * 300 = 300

        adult_fish = baby_fish -(baby_fish*0.1) #เดือนที่สาม ปลาโตเต็มวัยจากลูกปลาที่ลด 10 % แล้วก็เป็นปลาโตเต็มวัยที่ลดอีก 10% = baby_fish - (baby_fish*0.1) = 243
        baby_fish = egg_pp - (egg_pp*0.1)#เดือนที่สาม จากไข่กลายเป็นโดยเป็นลูกปลา แต่ลดลง10% = ไข่ที่ลดไปแล้ว 10% = 270
        egg_pp = pp_born * 300 #เดือนที่สาม 1 คู่ที่พร้อมผสมพันธ์จะผสมพันธ์กันแล้วออกไข่ในเดือนที่สองทันที่ 1 * 300 = 300
        print(f"ปีที่ {y} เดือนที่ {i} มีปลาทั้งหมด {round(adult_fish+n+baby_fish)}")
        n += adult_fish
      elif i > 3:
        adult_fish = baby_fish - (baby_fish * 0.1)
        n += adult_fish
        pp_born = n // 2
        baby_fish = egg_pp - (egg_pp*0.1)
        egg_pp = pp_born * 300
        if i % 3 == 0:
          print(f"ปีที่ {y} เดือนที่ {i} มีปลาทั้งหมด {round(n+baby_fish)}")
    if y >= 4:
      print(f"ปีที่ {y+1} ปลาหมอปีที่{remove+1} ตายทั้งหมด {year_offish[remove]}")
      n -= year_offish[remove]
      remove += 1
    year_offish.append(round(n+baby_fish))
n = 2
p = 10
simulate_fish_population(n, p)

ปีที่ 1 เดือนที่ 3 มีปลาทั้งหมด 515
ปีที่ 1 เดือนที่ 6 มีปลาทั้งหมด 158573
ปีที่ 1 เดือนที่ 9 มีปลาทั้งหมด 1030098278
ปีที่ 1 เดือนที่ 12 มีปลาทั้งหมด 660919791413
ปีที่ 2 เดือนที่ 3 มีปลาทั้งหมด 30122448241916
ปีที่ 2 เดือนที่ 6 มีปลาทั้งหมด 9282861195296924
ปีที่ 2 เดือนที่ 9 มีปลาทั้งหมด 60253449109616238592
ปีที่ 2 เดือนที่ 12 มีปลาทั้งหมด 38672499647717782323200
ปีที่ 3 เดือนที่ 3 มีปลาทั้งหมด 1761977585945330474549248
ปีที่ 3 เดือนที่ 6 มีปลาทั้งหมด 542990172252837843038109696
ปีที่ 3 เดือนที่ 9 มีปลาทั้งหมด 3524455447791716509548183289856
ปีที่ 3 เดือนที่ 12 มีปลาทั้งหมด 2262102901614115954367615807258624
ปีที่ 4 เดือนที่ 3 มีปลาทั้งหมด 103064830203733817963484015568617472
ปีที่ 4 เดือนที่ 6 มีปลาทั้งหมด 31761578780532407964014381563891417088
ปีที่ 4 เดือนที่ 9 มีปลาทั้งหมด 206158923464619301186388165387187329695744
ปีที่ 4 เดือนที่ 12 มีปลาทั้งหมด 132319079038197467716251915338186646873964544
ปีที่ 5 ปลาหมอปีที่1 ตายทั้งหมด 660919791413
ปีที่ 5 เดือนที่ 3 มีปลาทั้งหมด 602865740

2.	ให้เขียน function find_mismatch ซึ่งรับ string มา 2 ค่า โดยจะส่งค่ากลับดังนี้
- 0 เมื่อ string ทั้ง 2 ตัว เหมือนกัน โดยไม่สนใจ case
- 1 เมื่อ string 1 จะเหมือน string 2 โดยการลบและ/หรือเพิ่มตัวอักษรเพียง 1 ตัว
- 2 เมื่อ string ไม่เข้าเกณฑ์ 0 หรือ 1


| String  1| 	String2	|ผลลัพธ์|
|----------|----------|------|
|Python|	Java	|2|
|book	 |  boot	|1|
|fan	 |  fun	  |1|
|sin	 | sink	  |1 เพราะเพิ่ม k ใน str2 แล้วจะเหมือนกัน
|Dog	 | dog	  |0
|poke	 | spoke	|1 เพิ่ม s ใน str2 แล้วเหมือนกัน
|poker |	poke	|1 ตัด r ใน str1 ออกแล้วเหมือนกัน






In [ ]:
def find_mismatch(str1, str2):
    if str1.lower() == str2.lower(): # ถ้าตัวอักษรทุกตัวมีค่าเท่ากัน
        return 0
    if len(str1) == len(str2): # ตรวจสอบกรณีที่สามารถเพิ่มหรือลบตัวอักษรเพียง 1 ตัว
        diff_count = check_differnce(str1,str2) #จะตรวจสอบว่ามีตัวอักษรต่างกันเพียง 1 ตัวหรือไม่ ถ้ามีจะแสดงค่า 1
        if diff_count <= 2:
            return 1
    elif len(str1) > len(str2): # ตรวจสอบว่าถ้าตัวอักษรของชุดที่ 1 มากกว่าชุดที่ 2
        for i in range(len(str1)):
            if str1[:i] + str1[i+1:] == str2:# เป็นการตรวจสอบว่าถ้าลบ i ออกจาก str1 แล้วจะเท่ากับ str2 หรือไม่ ทั้งนี้ก็การลบstr1
                return 1
    else:# ตรวจสอบว่าถ้าตัวอักษรของชุดที่ 2 มากกว่าชุดที่ 2
        for i in range(len(str2)):
            if str2[:i] + str2[i+1:] == str1:# เป็นการตรวจสอบว่าถ้าลบ i ออกจาก str1 แล้วจะเท่ากับ str2 หรือไม่ ทั้งนี้คือการเพิ่ม str1
                return 1
    return 2
def check_differnce(str1,str2):
    count = 0
    for s1 in str1:
        if s1 not in str2:
            count += 1
    for s2 in str2:
        if s2 not in str1:
            count += 1
    return count

str1 = "poker"
str2 = "poke"
result = find_mismatch(str1, str2)
print(result)



1


3.	จากข้อ 1 ให้เขียนฟังก์ชันชื่อ spelling_correction โดยรับ 2 argument ตัวแรกเป็นประโยค (string) และตัวที่ 2 เป็น list ของคำ (correct_spells) โดยฟังก์ชันนี้มีหน้าที่ตรวจสอบแต่ละ word ใน input string กับคำที่อยู่ใน correct_spells โดยค่าที่คืนกลับมาจะมีดังนี้ (พยายามเรียกใช้ฟังก์ชันในข้อ 1)
-	ถ้าคำที่อยู่ในประโยค ตรงกับคำที่อยู่ใน correct_spells ทุกอย่าง ก็จะ copy ไปที่ output string
-	ถ้าคำที่อยู่ในประโยค ต่างจากคำที่อยู่ใน correct_spells โดยต่างกัน 1 ตัวอักษร โดยการเปลี่ยน การเพิ่ม หรือการลบ 1 ตัวอักษร คำที่อยู่ในประโยคจะถูกเปลี่ยนโดยคำที่อยู่ใน correct_spells และนำไปใส่ output string
-	ถ้าคำที่ไม่พบในเงื่อนไขข้างต้นให้นำคำนั้นไปใส่ output string ได้เลย
-	คำที่ประกอบด้วย 1 หรือ 2 ตัวอักษรจะไม่ตรวจสอบ ให้นำคำนั้นไปใส่ output string ได้เลย
-	ถ้ามี 2 คำใน correct_spells ที่ตรงตามเงื่อนไข ให้ใช้คำแรก
-	ไม่สนใจตัวใหญ่ ตัวเล็ก
-	Input string จะมีได้เพียงอักษรภาษาอังกฤษเท่านั้น
-	ในแต่ละคำจะคั่นด้วย 1 space ถ้ามี space มากกว่านั้นให้ตัดออก และตัด space จากหัวท้ายประโยค

|ประโยค	|correct_spells	|output string |
|-------|---------------|-------------|
|Thes is the Firs cas	|[‘that’,’first’,’case’,’car’]|	thes is the first car|
|programming is fan and easy	|[‘programming’,’this’,’fun’,’easy’,book’]	|programming is fun and easy|
|Thes is vary essy	|[‘this’,’is’,’very’,’easy’]	|this is very easy|
|Wee ipve Pythen	|[‘we’,’live’,’ln’,’Python’]	|we live python|




In [ ]:
word_correct = 	['programming','this','fun','easy','book','that','first','case','car','is','very','we','live','ln','python']
sentense = 'Thes is the Firs cas'
def find_mismatch(str1, str2):
    if str1.lower() == str2.lower(): # ถ้าตัวอักษรทุกตัวมีค่าเท่ากัน
        return str1
    if len(str1) == len(str2): # ตรวจสอบกรณีที่สามารถเพิ่มหรือลบตัวอักษรเพียง 1 ตัว
        diff_count = check_differnce(str1,str2) #จะตรวจสอบว่ามีตัวอักษรต่างกันเพียง 1 ตัวหรือไม่ ถ้ามีจะแสดงค่า 1
        if diff_count <= 2:
            return str2
    elif len(str1) > len(str2): # ตรวจสอบว่าถ้าตัวอักษรของชุดที่ 1 มากกว่าชุดที่ 2
        for i in range(len(str1)):
            if str1[:i] + str1[i+1:] == str2:# เป็นการตรวจสอบว่าถ้าลบ i ออกจาก str1 แล้วจะเท่ากับ str2 หรือไม่ ทั้งนี้ก็การลบstr1
                return str2
    else:# ตรวจสอบว่าถ้าตัวอักษรของชุดที่ 2 มากกว่าชุดที่ 2
        for i in range(len(str2)):
            if str2[:i] + str2[i+1:] == str1:# เป็นการตรวจสอบว่าถ้าลบ i ออกจาก str1 แล้วจะเท่ากับ str2 หรือไม่ ทั้งนี้คือการเพิ่ม str1
                return str2
    return str1
def check_differnce(str1,str2):
    count = 0
    for s1 in str1:
        if s1 not in str2:
            count += 1
    for s2 in str2:
        if s2 not in str1:
            count += 1
    return count

def spelling_correction(input_string, correct_spells):
    output_string = []
    input_string = input_string.lower()
    list_string = input_string.split(' ')
    for s1 in list_string:
        for c1 in correct_spells:
            if len(s1) <= 2 :
                output_string.append(s1)
                break
            else:
                if check_differnce(s1,c1) <= 2:
                    output_string.append(find_mismatch(s1,c1))
                    break
                else:
                    continue

    return output_string
sentense_correct = spelling_correction(sentense, word_correct)
print(" ".join(sentense_correct))

this is the first case


4. ให้เขียนฟังก์ชัน find_word_horizontal ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามแถวของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
	word='cat'
	find_word_horizontal(crosswords,word)
```

Output
   [2,1]


In [ ]:
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
def find_word_horizontal(crosswords,word):
    word_split = []
    word_split += word

    for row in range(len(crosswords)):
        for i in range(len(crosswords[row]) - len(word_split) + 1):# ให้วนตามจำนวนที่จะได้ค่าครบคือ กำหนดไว้ค่าต้องครบ 3 ตัวเพราะฉะนั้นการจับคู่จะเริ่มเป็น abc bcd โดยจะวนแค่ 2 รอบเท่านั้น
            pair = crosswords[row][i:i+len(word_split)]
            if pair == word_split:
                print(f"[{row},{i}]")

find_word_horizontal(crosswords,word)

[2,1]


5. ให้เขียนฟังก์ชัน find_word_vertical ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามคอลัมน์ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

ตัวอย่าง
```
	crosswords=[['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t',' e','t','k']]
	word='cat'
	find_word_vertical(crosswords,word)
```

Output
   [1,0]


In [ ]:
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
def find_word_vertical(crosswords,word):
    word_split = []
    word_split += word
    selected_word = []
    for col in range(len(crosswords)):
        start_point = 0
        end_point = len(word_split)
        for loop_len in range(len(crosswords)- len(word_split) + 1):
            selected_word = []
            for i in crosswords[start_point:end_point]:
                selected_word += i[col]
                if selected_word == word_split:
                    print(f"[{loop_len},{col}]")
                    return 0
            start_point += 1
            end_point += 1


find_word_vertical(crosswords,word)

[1,0]


0

6.	ให้เขียนฟังก์ชัน capitalize_word_in_crossword จะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตาม row และ column ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบจะเปลี่ยนเป็นตัวใหญ่และ และส่งคืน list ที่แก้ไขแล้ว แต่ถ้าไม่เจอจะส่ง list เดิมกลับมา ให้ใช้ฟังก์ชันตามข้อ 3 และ 4 ช่วย

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','x','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
```
จะส่งค่ากลับ
```
 [['s','d','o','g'],
  ['C','u','c','m'],
  ['A','x','a','t'],
  ['T','e','t','k']]
```
```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
จะส่งค่ากลับ                   
[['s','d','o','g'],
 ['c','u','c','m'],
 ['a','C','A','T'],
 ['t','e','t','k']]
```




In [ ]:
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
def find_word_vertical(crosswords,word):
    word_split = []
    word_split += word
    selected_word = []
    for col in range(len(crosswords)):
        start_point = 0
        end_point = len(word_split)
        for loop_len in range(len(crosswords)- len(word_split) + 1):
            selected_word = []
            for i in crosswords[start_point:end_point]:
                selected_word += i[col]
                if selected_word == word_split:
                    result = f"{loop_len}{col}"
                    return result
            start_point += 1
            end_point += 1
def find_word_horizontal(crosswords,word):
    word_split = []
    word_split += word

    for row in range(len(crosswords)):
        for i in range(len(crosswords[row]) - len(word_split) + 1):
            pair = crosswords[row][i:i+len(word_split)]
            if pair == word_split:
                result = f"{row}{i}"
                return result


def capitalize_word_in_crossword(crosswords,word):
    positon_found = []
    positon_found = find_word_horizontal(crosswords,word)
    if positon_found != None:
        rows = int(positon_found[0])
        col = int(positon_found[1])
        i = 0
        while i < len(word):
            crosswords[rows][col+i] = crosswords[rows][col+i].upper()
            i += 1
    positon_found = find_word_vertical(crosswords,word)
    if positon_found != None:
        rows = int(positon_found[0])
        col = int(positon_found[1])
        i = 0
        while i < len(word):
            crosswords[rows+i][col] = crosswords[rows+i][col].upper()
            i += 1
    return crosswords

crosswords = capitalize_word_in_crossword(crosswords,word)
print("crosswords = [")
for row in crosswords:
    print("    " + str(row) + ",")
print("]")

crosswords = [
    ['s', 'd', 'o', 'g'],
    ['C', 'u', 'c', 'm'],
    ['A', 'C', 'A', 'T'],
    ['T', 'e', 't', 'k'],
]
